# Generated by Django 6.1 on 2026-09-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
